site_name: ゲームデザインバイブル
site_description: ゲームデザインの完全解説サイト（全35章）
site_author: （御社名）
theme:
  name: material
  language: ja
  features:
    - navigation.sections
    - navigation.top
    - toc.follow
    - content.code.annotate
    - search.suggest
    - search.highlight
markdown_extensions:
  - admonition
  - footnotes
  - tables
  - toc:
      permalink: true
extra_css:
  - styles/extra.css

nav:
  - 第1章 始めにゲームデザイナーありき: 第01章_始めにゲームデザイナーありき.md
  - 第2章 デザイナーは体験を創り出す: 第02章_デザイナーは体験を創り出す.md
  - 第3章 体験はプレイ環境で起こる: 第03章_体験はプレイ環境で起こる.md
  - 第4章 体験はゲームから生まれる: 第04章_体験はゲームから生まれる.md
  - 第5章 ゲームを構成する要素: 第05章_ゲームを構成する要素.md
  - 第6章 構成要素がテーマを支える: 第06章_構成要素がテーマを支える.md
  - 第7章 ゲームはアイデアから始まる: 第07章_ゲームはアイデアから始まる.md
  - 第8章 ゲームはイテレーションで向上する: 第08章_ゲームはイテレーションで向上する.md
  - 第9章 ゲームはプレイヤーのために作られる: 第09章_ゲームはプレイヤーのために作られる.md
  - 第10章 体験はプレイヤーの脳内で起こる: 第10章_体験はプレイヤーの脳内で起こる.md
  - 第11章 プレイヤーの脳はモチベーションによって動かされる: 第11章_プレイヤーの脳はモチベーションによって動かされる.md
  - 第12章 一部の要素はゲームシステムである: 第12章_一部の要素はゲームシステムである.md
  - 第13章 ゲームシステムにはバランスが必須: 第13章_ゲームシステムにはバランスが必須.md
  - 第14章 パズルを支えるゲームシステム: 第14章_パズルを支えるゲームシステム.md
  - 第15章 プレイヤーはインタフェースを通じてゲームを遊ぶ: 第15章_プレイヤーはインタフェースを通じてゲームを遊ぶ.md
  - 第16章 体験は感情曲線で評価できる: 第16章_体験は感情曲線で評価できる.md
  - 第17章 ストーリーも体験の一種: 第17章_ストーリーも体験の一種.md
  - 第18章 ストーリーとゲーム構造は間接操作でうまく統合できる: 第18章_ストーリーとゲーム構造は間接操作でうまく統合できる.md
  - 第19章 ゲームとストーリーは世界で起こる: 第19章_ゲームとストーリーは世界で起こる.md
  - 第20章 世界にはキャラクターが含まれる: 第20章_世界にはキャラクターが含まれる.md
  - 第21章 世界には空間がある: 第21章_世界には空間がある.md
  - 第22章 世界のルック＆フィールはビジュアルで決まる: 第22章_世界のルック＆フィールはビジュアルで決まる.md
  - 第23章 他のプレイヤーと遊ぶゲームもある: 第23章_他のプレイヤーと遊ぶゲームもある.md
  - 第24章 一部のプレイヤーはコミュニティを形成する: 第24章_一部のプレイヤーはコミュニティを形成する.md
  - 第25章 ゲームデザイナーは通常、チームで作業する: 第25章_ゲームデザイナーは通常、チームで作業する.md
  - 第26章 チームはドキュメント経由でコミュニケーションをとることもある: 第26章_チームはドキュメント経由でコミュニケーションをとることもある.md
  - 第27章 素晴らしいゲームはプレイテストを通じて作られる: 第27章_素晴らしいゲームはプレイテストを通じて作られる.md
  - 第28章 チームは技術を使ってゲームを構築する: 第28章_チームは技術を使ってゲームを構築する.md
  - 第29章 あなたのゲームにはおそらくクライアントが存在する: 第29章_あなたのゲームにはおそらくクライアントが存在する.md
  - 第30章 ゲームデザイナーはクライアントにプレゼンテーションを行う: 第30章_ゲームデザイナーはクライアントにプレゼンテーションを行う.md
  - 第31章 ゲームデザイナーとクライアントがゲームに求めるのは利益である: 第31章_ゲームデザイナーとクライアントがゲームに求めるのは利益である.md
  - 第32章 ゲームはプレイヤーを変化させる: 第32章_ゲームはプレイヤーを変化させる.md
  - 第33章 ゲームデザイナーにはある種の責任が伴う: 第33章_ゲームデザイナーにはある種の責任が伴う.md
  - 第34章 ゲームデザイナーにはそれぞれの目的がある: 第34章_ゲームデザイナーにはそれぞれの目的がある.md
  - 第35章 おわりに: 第35章_おわりに.md
